import type { Match } from './types'

export const MATCHES_SEED: Match[] = [
  {
    id: 'ewc-final',
    competition: 'ewc',
    tournament: 'EWC 2026 · Riyad',
    stage: 'Grande finale · Bo5',
    bo: 5,
    team_a: {
      id: 't1',
      name: 'T1',
      region: 'LCK · Corée',
      cote: 1.85,
      form: 'WWWLW',
    },
    team_b: {
      id: 'geng',
      name: 'Gen.G',
      region: 'LCK · Corée',
      cote: 1.95,
      form: 'WWWWL',
    },
    start_time: Date.now() + 4 * 3600 * 1000 + 23 * 60 * 1000,
    mvps: [
      'Faker (Mid)',
      'Zeus (Top)',
      'Oner (Jgl)',
      'Gumayusi (ADC)',
      'Keria (Sup)',
      'Chovy (Mid)',
      'Kiin (Top)',
      'Canyon (Jgl)',
      'Peyz (ADC)',
      'Lehends (Sup)',
    ],
  },
  {
    id: 'ewc-petite',
    competition: 'ewc',
    tournament: 'EWC 2026 · Riyad',
    stage: 'Petite finale · Bo5',
    bo: 5,
    team_a: {
      id: 'g2',
      name: 'G2 Esports',
      region: 'LEC · Europe',
      cote: 1.7,
      form: 'WWWWL',
    },
    team_b: {
      id: 'drx',
      name: 'DRX',
      region: 'LCK · Corée',
      cote: 2.15,
      form: 'LWWWL',
    },
    start_time: Date.now() + 12 * 3600 * 1000,
    mvps: [
      'Caps (Mid)',
      'BrokenBlade (Top)',
      'Yike (Jgl)',
      'Hans Sama (ADC)',
      'Mikyx (Sup)',
      'BuLLDoG (Mid)',
      'Rascal (Top)',
      'Sponge (Jgl)',
      'Teddy (ADC)',
      'Jun DRX (Sup)',
    ],
  },
  {
    id: 'lec-final',
    competition: 'lec',
    tournament: 'LEC Summer 2026',
    stage: 'Finale · Bo5',
    bo: 5,
    team_a: {
      id: 'fnc',
      name: 'Fnatic',
      region: 'LEC · Europe',
      cote: 2.25,
      form: 'WWWLW',
    },
    team_b: {
      id: 'g2',
      name: 'G2 Esports',
      region: 'LEC · Europe',
      cote: 1.65,
      form: 'WWWWL',
    },
    start_time: Date.now() + 4 * 24 * 3600 * 1000,
    mvps: [
      'Humanoid (Mid)',
      'Oscarinin (Top)',
      'Razork (Jgl)',
      'Noah (ADC)',
      'Jun FNC (Sup)',
      'Caps (Mid)',
      'BrokenBlade (Top)',
      'Yike (Jgl)',
      'Hans Sama (ADC)',
      'Mikyx (Sup)',
    ],
  },
  {
    id: 'lec-petite',
    competition: 'lec',
    tournament: 'LEC Summer 2026',
    stage: 'Petite finale · Bo5',
    bo: 5,
    team_a: {
      id: 'koi',
      name: 'KOI',
      region: 'LEC · Europe',
      cote: 1.75,
      form: 'WWLWW',
    },
    team_b: {
      id: 'mad',
      name: 'MAD Lions',
      region: 'LEC · Europe',
      cote: 2.1,
      form: 'LWLWW',
    },
    start_time: Date.now() + 5 * 24 * 3600 * 1000,
    mvps: [
      'Aurora (Mid)',
      'Ruby (Top)',
      'Elyoya (Jgl)',
      'Comp (ADC)',
      'Alvaro (Sup)',
      'Nisqy (Mid)',
      'Chasy (Top)',
      'Elite (Jgl)',
      'Supa (ADC)',
      'Mersa (Sup)',
    ],
  },
  {
    id: 'lck-final',
    competition: 'lck',
    tournament: 'LCK Summer 2026',
    stage: 'Finale · Bo5',
    bo: 5,
    team_a: {
      id: 't1',
      name: 'T1',
      region: 'LCK · Corée',
      cote: 1.9,
      form: 'WWWLW',
    },
    team_b: {
      id: 'geng',
      name: 'Gen.G',
      region: 'LCK · Corée',
      cote: 1.9,
      form: 'WWWWL',
    },
    start_time: Date.now() + 6 * 24 * 3600 * 1000,
    mvps: [
      'Faker (Mid)',
      'Zeus (Top)',
      'Oner (Jgl)',
      'Gumayusi (ADC)',
      'Keria (Sup)',
      'Chovy (Mid)',
      'Kiin (Top)',
      'Canyon (Jgl)',
      'Peyz (ADC)',
      'Lehends (Sup)',
    ],
  },
  {
    id: 'lck-petite',
    competition: 'lck',
    tournament: 'LCK Summer 2026',
    stage: 'Petite finale · Bo5',
    bo: 5,
    team_a: {
      id: 'drx',
      name: 'DRX',
      region: 'LCK · Corée',
      cote: 1.8,
      form: 'WLWWW',
    },
    team_b: {
      id: 'hle',
      name: 'Hanwha Life',
      region: 'LCK · Corée',
      cote: 2.05,
      form: 'WWLWL',
    },
    start_time: Date.now() + 7 * 24 * 3600 * 1000,
    mvps: [
      'BuLLDoG (Mid)',
      'Rascal (Top)',
      'Sponge (Jgl)',
      'Teddy (ADC)',
      'Jun DRX (Sup)',
      'Zeka (Mid)',
      'Doran (Top)',
      'Peanut (Jgl)',
      'Viper (ADC)',
      'Delight (Sup)',
    ],
  },
]
